services:
  - type: web
    name: website01
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://website01.onrender.com
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: es
      - key: APP_FAKER_LOCALE
        value: es_ES
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_ENCRYPT
        value: "true"
      - key: SESSION_LIFETIME
        value: "120"
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
